export const arrayWorkLink = [
  { id: 1001, link: './img/banner_1.webp', alt: 'トマトジュースのバナー' },
  { id: 1002, link: './img/flier_1.webp', alt: '美容室のチラシ' },
  { id: 1003, link: './img/web_1.webp', alt: 'webサイト' },
  { id: 1004, link: './img/banner_1.webp', alt: 'トマトジュースのバナー' },
  { id: 1005, link: './img/flier_1.webp', alt: '美容室のポスター' },
  { id: 1006, link: './img/web_1.webp', alt: 'webサイト' },
  { id: 1007, link: './img/banner_1.webp', alt: 'トマトジュースのバナー' },
  { id: 1008, link: './img/flier_1.webp', alt: '美容室のチラシ' },
  { id: 1009, link: './img/web_1.webp', alt: 'webサイト' },
]

export const arrayLabel = [
  { number: 1, labelName: '個人制作' },
  { number: 2, labelName: 'チーム制作' },
]

export const arryaTag = [
  { value: 'bn', tagName: '#banner' },
  { value: 'web', tagName: '#web' },
  { value: 'fl', tagName: '#poster' },
  { value: 'ps', tagName: '#flier' },
]

export const arrayWorkDetail = [
  {
    id: 1001,
    title: 'トマトジュースのバナー',
    link: './img/tomato_bn.jpg',
    url: '',
    target: '30代〜40代 女性',
    purpose: '販売促進',
    point: '爽やかを感じさせる画像を使用した。',
    time: '3時間',
    size: '1080px×1080px',
    tool: 'Illustrator / Photoshop',
    value: 'bn',
    number: 1,
  },
  {
    id: 1002,
    title: '美容室のチラシ',
    link: './img/hairsalon_fl.jpg',
    url: '',
    target: '20代〜40代 女性',
    purpose: '認知度を上げ、来店してもらう',
    point: '居心地の良さを写真や色合いで表現した。',
    time: '5時間',
    size: '210mm×297mm',
    tool: 'Illustrator / Photoshop',
    value: 'fl',
    number: 1,
  },
  {
    id: 1003,
    title: 'webサイト',
    link: './img/web.png',
    url: 'http://127.0.0.1:5500/index.html',
    target: '20代〜40代 男性 ',
    purpose: 'リピート客を増やす',
    point: 'キャンペーン内容を全面に出した。',
    time: '24時間',
    size: '1280px×1610px',
    tool: 'Illustrator / Photoshop / figma',
    value: 'web',
    number: 2,
  },
  {
    id: 1004,
    title: '健康食品のバナー',
    link: './img/tomato_bn.jpg',
    url: '',
    target: '30代〜50代 女性',
    purpose: '販売促進',
    point: '気軽に続けられることを印象付けるキャッチコピーを記載した。',
    time: '2時間',
    size: '1080px×1080px',
    tool: 'Illustrator / Photoshop',
    value: 'bn',
    number: 1,
  },
  {
    id: 1005,
    title: 'ハンバーガーのポスター',
    link: './img/hairsalon_fl.jpg',
    url: '',
    target: '20代〜30代 男性',
    purpose: '商品の販売促進',
    point: 'ハンバーガーのボリューム感を出すために、画像を大きく使用した。',
    time: '3時間',
    size: '210mm×297mm',
    tool: 'Illustrator / Photoshop',
    value: 'ps',
    number: 1,
  },
  {
    id: 1006,
    title: '学校のサイト',
    link: './img/web.png',
    url: 'http://127.0.0.1:5500/index.html',
    target: '高校生の子供を持つ女性',
    purpose: '認知度向上',
    point: '学校生活がイメージできるように写真を多く使用した。',
    time: '3日',
    size: '1280px×2000px',
    tool: 'Illustrator / Photoshop',
    value: 'web',
    number: 2,
  },
  {
    id: 1007,
    title: '洋服のクーポンのバナー',
    link: './img/tomato_bn.jpg',
    url: '',
    target: '20代 女性',
    purpose: '販売促進',
    point: 'お得感を表現した。',
    time: '3時間',
    size: '1080px×1080px',
    tool: 'Illustrator / Photoshop',
    value: 'bn',
    number: 2,
  },
  {
    id: 1008,
    title: '住宅のチラシ',
    link: './img/hairsalon_fl.jpg',
    url: '',
    target: '30代〜40代 女性',
    purpose: '販売促進',
    point: '爽やかを感じさせる画像を使用した。',
    time: '3時間',
    size: '1080px×1080px',
    tool: 'Illustrator / Photoshop',
    value: 'fl',
    number: 1,
  },
  {
    id: 1009,
    title: '香水のサイト',
    link: './img/web.png',
    url: 'http://127.0.0.1:5500/index.html',
    target: '30代〜40代 女性',
    purpose: '販売促進',
    point: '爽やかを感じさせる画像を使用した。',
    time: '3時間',
    size: '1080px×1080px',
    tool: 'Illustrator / Photoshop',
    value: 'web',
    number: 1,
  },
]
